### ISSUE TITLE
grpc_bert_client.py  error

### ISSUE THREAD

**Issue by Neo-Vo** [panda-baba/bert_punct#1]
when i run  grpc_bert_client.py 
ImportError: cannot import name 'create_tokenizer_from_hub_module' from 'bert_punct_1'
But it seems that there is no create_tokenizer_from_hub_module in bert_punct_1.

**Comment by karanmakhija867** [comment]
@Newzq: The grpc_bert_client.py file was outdated. I have uploaded the new version. Let me know if it is working.

**Comment by Neo-Vo** [comment]
> The grpc_bert_client.py file was outdated. I have uploaded the new version. Let me know if it is working.

it's working,thx
