### ISSUE TITLE
Pre-trained weights

### ISSUE THREAD

**Issue by bharat-patidar** [panda-baba/bert_punct#3]
Hi,
I am trying to explore this solution and already downloaded pre-trained BERT model but want to know if we need any other pre-trained weights apart from BERT base uncased model to deploy and test this solution.
I am wondering if we need weights for BiLSTM-CRF architecture and in case it's required, it will be wonderful if you don't mind sharing the same.

Thanks

**Comment by karanmakhija867** [comment]
I don't use any other pre-trained weights apart from BERT.

**Comment by bharat-patidar** [comment]
Thanks for the quick response @panda-baba 
Can you please provide more details on files which are required to run model server?
Do we need to create .pb file from bert checkpoint files? If yes, what should be the structure of other files inside _models_for_serving_ folder?

**Comment by karanmakhija867** [comment]
Yes, we need to use the files created with checkpointing. The structure would be clear from the other [read me](https://github.com/panda-baba/bert_punct/blob/master/DEPLOY.md) file provided. Sorry for the late reply. It is really an old project and I am not actively tracking it.
