### ISSUE TITLE
Further work

### ISSUE THREAD

**Issue by AetherPrior** [panda-baba/bert_punct#4]
Hey, I'm part of the team for continuing the sentence unit detection project. I have been linked to this repository. I just want to know if there is any report of sorts that I can refer to? 
Thanks!

**Comment by karanmakhija867** [comment]
We published a paper at APSIPA 2019. [Here](http://www.apsipa.org/proceedings/2019/pdfs/60.pdf) is the link to the paper.

**Comment by AetherPrior** [comment]
Sorry for the late reply. Thank you for the link to the paper @panda-baba  
Can I use the issue tracker in case I have any other question?

**Comment by karanmakhija867** [comment]
Instead, we can use email.
